worker_processes auto;
pid /tmp/nginx.pid; # Важливо для non-root

events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    
    # Gzip Compression (Hardcore)
    gzip on;
    gzip_types text/plain text/css application/javascript text/html;

    server {
        listen 8080; # Non-root порт
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        # Увімкнення Server Side Includes (для виведення hostname)
        location / {
            ssi on;
        }

        # Caching headers для статики (Hardcore)
        location ~* \.(css|js|png|jpg|jpeg|gif|ico)$ {
            expires 1y;
            add_header Cache-Control "public, no-transform";
        }

        # Custom 404 Error page (Hardcore)
        error_page 404 /404.html;
        location = /404.html {
            internal;
        }
    }
}
