worker_processes auto;
# Запуск від non-root користувача (визначимо в Dockerfile)
pid /tmp/nginx.pid; 

events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    server {
        listen 8080; # Порт > 1024 для non-root
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
            add_header Cache-Control "public, max-age=3600";
        }
    }
}
