name: Terraform

on:
  push:
    branches:
      - feature-tf-level-5-Alina-Dmytruk

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    # Вказуємо Terraform заходити в твою папку з кодом
    defaults:
      run:
        working-directory: ./pract16_lvl4

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        env:
          TF_VAR_MONGODB_ATLAS_PUBLIC_KEY_DMYTRUK: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY_DMYTRUK }}
          TF_VAR_MONGODB_ATLAS_PRIVATE_KEY_DMYTRUK: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY_DMYTRUK }}
          TF_VAR_MONGODB_ATLAS_ORGANIZATION_ID_DMYTRUK: ${{ secrets.MONGODB_ATLAS_ORGANIZATION_ID_DMYTRUK }}

      - name: Terraform Plan
        run: terraform plan
        env:
          TF_VAR_MONGODB_ATLAS_PUBLIC_KEY_DMYTRUK: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY_DMYTRUK }}
          TF_VAR_MONGODB_ATLAS_PRIVATE_KEY_DMYTRUK: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY_DMYTRUK }}
          TF_VAR_MONGODB_ATLAS_ORGANIZATION_ID_DMYTRUK: ${{ secrets.MONGODB_ATLAS_ORGANIZATION_ID_DMYTRUK }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_MONGODB_ATLAS_PUBLIC_KEY_DMYTRUK: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY_DMYTRUK }}
          TF_VAR_MONGODB_ATLAS_PRIVATE_KEY_DMYTRUK: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY_DMYTRUK }}
          TF_VAR_MONGODB_ATLAS_ORGANIZATION_ID_DMYTRUK: ${{ secrets.MONGODB_ATLAS_ORGANIZATION_ID_DMYTRUK }}
