name: Terraform

on:
  push:
    branches:
      - feature/terraform-darvai

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform-atlas

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
        env:
          TF_VAR_MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY_DARVAI }}
          TF_VAR_MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY_DARVAI }}
          TF_VAR_MONGODB_ATLAS_ORGANIZATION_ID: ${{ secrets.MONGODB_ATLAS_ORGANIZATION_ID_DARVAI }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY_DARVAI }}
          TF_VAR_MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY_DARVAI }}
          TF_VAR_MONGODB_ATLAS_ORGANIZATION_ID: ${{ secrets.MONGODB_ATLAS_ORGANIZATION_ID_DARVAI }}
